// Netlify Function: /api/bms-extract
// Accepts multipart form data: cv (PDF or Word), notes, roleTitle, client
// Returns: { candidateData, cvBase64, cvMimeType, cvOriginalName, cvText }
//
// COMPLIANCE RULE — read before touching this file:
// "Right to Work" and "Other Processes" are NEVER generated by the AI, even
// as a "best guess" or fallback. Both are compliance-relevant facts that
// must come from an explicit statement by the consultant, not an inference
// from the CV (a CV address, driving licence, or nationality mention does
// not confirm current legal work status). This function always returns
// empty strings for both — the review step in the UI requires the
// consultant to fill them in directly, and bms-generate-pdf.mjs refuses to
// generate a document with rightToWork blank.
//
// Only "relevantExperience" (and "noticePeriod", if explicitly stated in
// notes) are AI-populated — both are ordinary CV/notes content, not
// compliance facts.

import { Buffer } from "buffer";

const MAX_SIZE = 5.5 * 1024 * 1024;

// ─── Multipart parser (byte-level, no string boundary matching) ──────────────

function indexOfBytes(haystack, needle, start = 0) {
  outer: for (let i = start; i <= haystack.length - needle.length; i++) {
    for (let j = 0; j < needle.length; j++) {
      if (haystack[i + j] !== needle[j]) continue outer;
    }
    return i;
  }
  return -1;
}

function parseMultipart(buf, contentType) {
  const boundaryMatch = contentType.match(/boundary=("?)([^";,\s]+)\1/i);
  if (!boundaryMatch) throw new Error("No boundary found in Content-Type");
  const boundaryBytes = Buffer.from(boundaryMatch[2], "utf8");
  const CR = 13, LF = 10, DASH = 45;

  const startBoundary = Buffer.concat([Buffer.from([DASH, DASH]), boundaryBytes, Buffer.from([CR, LF])]);
  const delimiter = Buffer.concat([Buffer.from([CR, LF, DASH, DASH]), boundaryBytes]);

  const fields = {};
  let file = null;

  let pos = indexOfBytes(buf, startBoundary, 0);
  if (pos === -1) {
    const altStart = Buffer.concat([Buffer.from([DASH, DASH]), boundaryBytes]);
    pos = indexOfBytes(buf, altStart, 0);
    if (pos === -1) throw new Error("Could not find start boundary");
    pos += altStart.length;
    if (buf[pos] === CR && buf[pos + 1] === LF) pos += 2;
  } else {
    pos += startBoundary.length;
  }

  const headerSep = Buffer.from([CR, LF, CR, LF]);

  while (pos < buf.length) {
    const headerEnd = indexOfBytes(buf, headerSep, pos);
    if (headerEnd === -1) break;

    const headerStr = buf.slice(pos, headerEnd).toString("utf8");
    const bodyStart = headerEnd + 4;

    let bodyEnd = indexOfBytes(buf, delimiter, bodyStart);
    if (bodyEnd === -1) bodyEnd = buf.length;

    const partBody = buf.slice(bodyStart, bodyEnd);

    const dispositionMatch = headerStr.match(/Content-Disposition:[^\r\n]*name="([^"]+)"/i);
    const filenameMatch = headerStr.match(/Content-Disposition:[^\r\n]*filename="([^"]+)"/i);
    const mimeMatch = headerStr.match(/Content-Type:\s*([^\r\n]+)/i);

    if (dispositionMatch) {
      const name = dispositionMatch[1];
      if (filenameMatch) {
        file = {
          fieldname: name,
          originalname: filenameMatch[1],
          mimetype: mimeMatch ? mimeMatch[1].trim() : "application/octet-stream",
          buffer: partBody,
          size: partBody.length,
        };
      } else {
        fields[name] = partBody.toString("utf8");
      }
    }

    pos = bodyEnd + delimiter.length;
    if (buf[pos] === DASH && buf[pos + 1] === DASH) break;
    if (buf[pos] === CR && buf[pos + 1] === LF) pos += 2;
  }

  return { fields, file };
}

// ─── CV text extraction ───────────────────────────────────────────────────────

async function extractTextFromPDF(buffer) {
  const { default: pdfParse } = await import("pdf-parse/lib/pdf-parse.js");
  const data = await pdfParse(buffer);
  return data.text || "";
}

async function extractTextFromWord(buffer) {
  const mammoth = await import("mammoth");
  const result = await mammoth.extractRawText({ buffer });
  return result.value || "";
}

// ─── LLM extraction — relevantExperience + noticePeriod ONLY ─────────────────

const SYSTEM_PROMPT = `You are a recruitment data extraction engine for BMS (Bristol Myers Squibb) candidate submissions via Beeline.
Output ONLY a raw JSON object — no markdown, no explanation, no code fences.

Your ONLY job is to populate "relevantExperience" and, if explicitly stated in the notes, "noticePeriod". You must NOT attempt to determine right-to-work status, worker classification (PAYE/Ltd/Umbrella), or ongoing interview processes elsewhere — those are compliance-relevant facts that are handled separately by a human, never inferred by you, and any value you produced for them would be discarded.

Output schema:
{
  "relevantExperience": ["bullet 1", "bullet 2", "bullet 3"],
  "noticePeriod": "string, or empty string if not explicitly stated in notes"
}`;

async function extractWithLLM(cvText, notes, roleTitle, client) {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) throw new Error("ANTHROPIC_API_KEY is not set in Netlify environment variables.");

  const rolePart = roleTitle || "the role";
  const clientPart = client || "BMS";

  const userMessage = "=== INTERVIEW NOTES ===\n"
    + (notes || "No notes provided.")
    + "\n=== END NOTES ===\n\n=== CV TEXT ===\n"
    + cvText
    + "\n=== END CV ===\n\n"
    + "Return ONLY this JSON object:\n"
    + "{\n"
    + "  \"relevantExperience\": [\n"
    + "    \"3-4 short bullet lines (one sentence each) tying the candidate's real CV experience to the " + rolePart + " role at " + clientPart + ". Name specific skills, systems, and sector experience. No personal contact details. Keep each line short — this fills a compact table cell, not a full page.\"\n"
    + "  ],\n"
    + "  \"noticePeriod\": \"Only if explicitly stated in the interview notes above (e.g. '2 months', '4 weeks'). Empty string if not stated — do not guess from the CV.\"\n"
    + "}";

  const response = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: { "Content-Type": "application/json", "x-api-key": apiKey, "anthropic-version": "2023-06-01" },
    body: JSON.stringify({
      model: "claude-sonnet-4-6",
      max_tokens: 1024,
      system: SYSTEM_PROMPT,
      messages: [{ role: "user", content: userMessage }],
    }),
  });

  if (!response.ok) {
    const err = await response.text();
    throw new Error("Claude API error " + response.status + ": " + err);
  }

  const result = await response.json();
  const content = result.content && result.content[0] && result.content[0].text;
  if (!content) throw new Error("Claude returned empty response");

  const jsonMatch = content.match(/\{[\s\S]*\}/);
  if (!jsonMatch) throw new Error("Could not parse JSON from Claude response. Click Extract again.");

  const parsed = JSON.parse(jsonMatch[0]);
  return {
    relevantExperience: Array.isArray(parsed.relevantExperience) ? parsed.relevantExperience : [],
    noticePeriod: typeof parsed.noticePeriod === "string" ? parsed.noticePeriod : "",
  };
}

// Very light candidate-name extraction — first non-empty line of the CV that
// looks like a name (short, no digits, no @ sign). This is a fallback only;
// the review step lets the consultant correct it, so a wrong guess here
// never reaches the final document unreviewed. Excludes known BMS template
// boilerplate phrases — if a candidate's own CV file already has a filled
// BMS submission table prepended to it (e.g. prepared earlier by someone
// else), the very first line of extracted text can literally be "Candidate
// Submission" or similar, which would otherwise get guessed as the name.
const NAME_GUESS_EXCLUDE = [
  "candidate submission", "candidate name", "notice period", "relevant experience",
  "right to work", "other processes", "bristol myers squibb", "bms",
];
function guessCandidateName(cvText) {
  const lines = (cvText || "").split("\n").map((l) => l.trim()).filter(Boolean);
  for (const line of lines.slice(0, 8)) {
    if (line.length > 2 && line.length < 60 && !/\d/.test(line) && !line.includes("@")) {
      if (NAME_GUESS_EXCLUDE.includes(line.toLowerCase())) continue;
      return line;
    }
  }
  return "";
}

// ─── Handler ──────────────────────────────────────────────────────────────────

export const handler = async (event) => {
  if (event.httpMethod !== "POST") {
    return { statusCode: 405, body: JSON.stringify({ error: "Method not allowed" }) };
  }

  try {
    const contentType = event.headers["content-type"] || event.headers["Content-Type"] || "";
    if (!contentType.includes("multipart/form-data")) {
      return { statusCode: 400, body: JSON.stringify({ error: "Request must be multipart/form-data" }) };
    }

    const bodyBuffer = event.isBase64Encoded
      ? Buffer.from(event.body, "base64")
      : Buffer.from(event.body || "", "utf8");

    const { fields, file } = parseMultipart(bodyBuffer, contentType);

    const notes = fields.notes || "";
    const roleTitle = fields.roleTitle || "";
    const client = fields.client || "";

    if (!file) {
      return { statusCode: 400, body: JSON.stringify({ error: "No CV file uploaded. Please attach a PDF or Word file." }) };
    }

    const allowedTypes = [
      "application/pdf",
      "application/msword",
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    ];
    const isPdf = file.mimetype === "application/pdf" || file.originalname.toLowerCase().endsWith(".pdf");
    const isWord = file.originalname.toLowerCase().endsWith(".docx") || file.originalname.toLowerCase().endsWith(".doc");

    if (!allowedTypes.includes(file.mimetype) && !isPdf && !isWord) {
      return { statusCode: 400, body: JSON.stringify({ error: "Only PDF and Word (.doc, .docx) files are accepted." }) };
    }

    if (file.size > MAX_SIZE) {
      return { statusCode: 413, body: JSON.stringify({ error: "CV file exceeds 5.5 MB. Please compress it and re-upload." }) };
    }

    let cvText = "";
    try {
      cvText = isPdf ? await extractTextFromPDF(file.buffer) : await extractTextFromWord(file.buffer);
    } catch (err) {
      return {
        statusCode: 422,
        body: JSON.stringify({ error: "Could not extract text from CV: " + err.message + ". Try re-saving the file and re-uploading." }),
      };
    }

    if (!cvText.trim()) {
      return { statusCode: 422, body: JSON.stringify({ error: "CV text was empty or unreadable." }) };
    }

    let aiData;
    try {
      aiData = await extractWithLLM(cvText, notes, roleTitle, client);
    } catch (err) {
      return {
        statusCode: 500,
        body: JSON.stringify({ error: "Could not parse AI response: " + err.message + ". Click Extract again — it usually succeeds on retry." }),
      };
    }

    const candidateData = {
      candidateName: guessCandidateName(cvText),
      noticePeriod: aiData.noticePeriod,
      relevantExperience: aiData.relevantExperience,
      // Deliberately blank — see compliance note at the top of this file.
      // The UI must require these to be filled in before a document can be
      // generated; never pre-fill them, even with "N/A".
      rightToWork: "",
      otherProcesses: "",
    };

    const cvBase64 = file.buffer.toString("base64");

    return {
      statusCode: 200,
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        candidateData,
        cvBase64,
        cvMimeType: isPdf ? "application/pdf" : file.mimetype,
        cvOriginalName: file.originalname,
        // Word CVs can't be embedded directly into the final PDF — send the
        // extracted text back so bms-generate-pdf.mjs can paginate it.
        cvText: isPdf ? "" : cvText,
      }),
    };
  } catch (err) {
    console.error("[bms-extract]", err);
    return { statusCode: 500, body: JSON.stringify({ error: "Server error: " + err.message }) };
  }
};
